version: '3.9'

services:
  db:
    container_name: theshop-db
    build: ./
    restart: always
    environment:
      MYSQL_DATABASE: 'TheShopDB'
      MYSQL_ROOT_PASSWORD: 'P@ssw0rd'
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - shop_network

volumes:
  mysql_data:
   
networks:
  shop_network:
   external: true