version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: theshop-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: TheShopDB
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - shop_network

volumes:
  mysql_data:

networks:
  shop_network: